application: vivianbrown
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /css
  static_dir: static/css

- url: /images
  static_dir: images

- url: /files
  static_dir: files

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /.*
  script: helloworld.py
